apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::430878334063:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::430878334063:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PZ75YU7GI7C5
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-16T01:47:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3208"
  uid: 32abb6b6-cd5d-4a0a-a7b2-fdfab04a1383
